version: '3'
services:
  malicious-connection-api:
    build: .
    restart: always
    volumes:
      - ./app:/app
      - ./models:/models
    working_dir: /app/
    ports:
      - "8003:8003"
    command: python -u ./main.py
